clean-css/clean-css

.travis.yml
One test fails on Windows.
```console
> clean-css@3.1.0-pre test C:\Users\xmr\Desktop\clean-css
> vows
·······················  ·······················································
················································································
············ ···································································
················································································
················································································
················································································
················································································
················································································ …
```
=> Travis: test node.js 0.12 too.

lib/imports/inliner.js, lib/selectors/source-map-stringifier.js, package.json, test/integration-test.js, test/selectors/optimizer-test.js, test/selectors/optimizers/simple-test.js, test/selectors/tokenizer-source-maps-test.js, test/selectors/tokenizer-test.js, test/source-map-test.js
@jakubpawlowicz: how about distributing cleancss-browser.js too? I find it very useful instead of me having to check out the source and do it myself.
=> Remove extra commas.

README.md
=> It's Sass, not SASS

History.md, lib/utils/input-source-map-tracker.js, test/source-map-test.js
Enables ingestion of inline, data-uri source maps.
=> Fixes #599 - inlined source maps.

README.md
Strings 319 and 322 are duplicated in file Readme.md
=> Delete duplicated description.

README.md
=> + online tools

appveyor.yml, package.json
* AppVeyor and node.js 5
* Dependency updates
=> Pulling in changes by @XhmikosR

lib/selectors/clean-up.js, test/selectors/simple-test.js
Fixes https://github.com/jakubpawlowicz/clean-css/issues/735.
=> Fix whitespace removal with escaped joining characters

lib/properties/wrap-for-optimizing.js, lib/tokenizer/extract-properties.js, test/integration-test.js
Fix #745
In v3.3.10 works ok, fails in v3.4.10
The problem was introduced in 96096402eaaeb4947afa7ecacba0982381a244f4
=> Don't skip !important rule with capital letters

README.md, bin/cleancss
Brings back #348, which had been undone during #370.
=> Note that rounding only applies to px values

README.md
Hey 👋 ,
the variable name in the usage demo has been mixed up.
=> Fix variable name typo in README

issue_template.md
Why:
* Not everyone read contributing guide so this should improve things slightly.
=> Adds a new issue template

lib/tokenizer/tokenize.js, test/fixtures/issue-1001-min.css, test/fixtures/issue-1001.css
- case of roundBracketLevel inferior to 0.
=> [#1001] Fix corrupted state of tokenizer

lib/optimizer/level-1/optimize.js
This is a fix for the issue I mentioned here:
https://github.com/jakubpawlowicz/clean-css/issues/1038
=> Fix incorrect stripping of quotes in font-variation-settings

History.md, lib/tokenizer/tokenize.js, test/bench.js
Few rather simple tricks pulled from a sleeve ;-) and our CSS tokenizer is 25% faster than before. Yay! Let's just squash those Windows bugs before merging.
=> Tokenizer improvements

README.md
Update node requirement in README
=> Update node requirement in README

README.md
There is no need to use third party plugins anymore.
I wrote some code that adapts clean-css for gulp.
=> Clean-css for gulp

website/README.md, website/package-lock.json, website/package.json, website/src/App.svelte, website/src/components/Navbar.svelte, website/webpack.config.js
This feature some badges to the website like the github stars and npm download. See a preview at https://johannchopin.github.io/clean-css/
=> Add navbar to website with social badges

History.md, lib/optimizer/level-1/optimize.js, lib/options/optimization-level.js, test/optimizer/level-1/optimize-test.js, test/options/optimization-level-test.js
Kudos to @Exotelis for bringing up the idea, however I decided that a more
customizable approach is needed here.
To optimize variables, there's a new `variableValueOptimizers` level 1 property,
see test/optimizer/level-1/optimize-test.js for details.
=> Adds customizable value optimizers for variables.

lib/optimizer/level-1/tidy-rules.js, test/optimizer/level-1/optimize-test.js
This pr is complements #1159.
`nth-last-child` and `nth-last-of-type` can minify in the same way as `nth-child` and `nth-of-type`.
=> Add optimization for nth-last-child and nth-last-of-type
