README.md, appveyor.yml
WIP until @jakubpawlowicz you add AppVeyor for the repository itself :)
Also, note that node.js 0.12 hasn't been deployed yet on AppVeyor. I have notified @FeodorFitsner so it shouldn't take long before it's been added.
=> Add AppVeyor for Windows tests.

bin/cleancss
```
C:\Users\xmr\Desktop>node -v & npm -v
v0.12.0
2.5.1
C:\Users\xmr\Desktop\>cleancss --help
Usage: cleancss [options] source-file, [source-file, ...]
Options:
-h, --help                     output usage information
-v, --version                  output the version number
-b, --keep-line-breaks         Keep line breaks
--s0                           Remove all special comments, i.e. /*! comment */
--s1                           Remove all special comments but the first one
-r, --root [root-path]         Set a root path to which resolve absolute @import rules
-o, --output [output-file]     Use [output-file] as output instead of STDOUT
-s, --skip-import              Disable @import processing
--skip-rebase                  Disable URLs rebasing
--skip-advanced                Disable …
```
=> bin/cleancss: use `console.log` instead of `util.puts`.

README.md
I've created a clean-css plugin for use with the [Lasso.js](https://github.com/lasso-js/lasso) module bundler, and added a reference to it in the plugin list section of the clean-css documentation in this PR.
=> Updates README.md plugin list with lasso-clean-css

lib/urls/rewrite.js, lib/utils/source-reader.js, test/integration-test.js
Prevent SourceReader to remove all quote in `url()`
=> fix #701 properties.urlQuotes doesn't work

README.md
Replacing old and unmaintained gulp plugin in favor of `gulp-clean-css`. I will be actively maintaining this project moving forward.
=> README: updating gulp plugin

lib/imports/inliner.js, test/protocol-imports-test.js
When an @import used a https url, the false protocol was tried to be used for the http proxy.
fixes #741
=> fix proxy issues on https @imports

lib/utils/compatibility.js, test/integration-test.js
Firefox does not support `:selection`, only `:-moz-selection`. This change adds `:selection` to the list of problematic selectors to prevent invalid rules from being created.
Also cleaned up the regex, `:` and `::` are equivalent in this regex, so reduced all section to just `:`.
=> Prevent rules with :selection from being merged

bin/cleancss, lib/clean.js, lib/selectors/simple.js, test/selectors/simple-test.js
Follow-up to #817. Doesn't fix the main issue (rounding-precision "-1" value in CLI), though improving a bit the situation.
- Cast value in the options object, as it's done for the other options.
- edit: Rather cast in the `buildPrecision()` function as it appears to be simpler.
- Avoid instructions if NaN, rather than be working by luck.
=> Strenghten handling of rounding-precision option

test/batch-test.js
`assertEqualLineByLine()` did not check if `expected` has the same number of lines as `actual`, which in turn cause `vow` to hang in some 100% CPU loop on Windows.
=> Re-enables batch tests on Windows.

lib/optimizer/level-2/properties/override-properties.js
`require` accepts a single operand.
That's crashing when bundling the source code with Webpack.
=> Fix wrong require arity

README.md, lib/reader/read-sources.js, test/module-test.js
This change makes it easier to specify the order in which sources are concatenated.  See issue jakubpawlowicz/clean-css#908 for details.
=> Extend readSources to accept array of source hashes

lib/clean.js
This PR adds the process method to clean-css so 
[optimize-css-assets-webpack-plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) can use it as css processor.
Closes issue https://github.com/jakubpawlowicz/clean-css/issues/943.
=> Add process method (compatibility with optimize-css-assets-webpack-plugin)

docs/index.html
While debugging https://github.com/jakubpawlowicz/clean-css/issues/955, I was confused why the special comments option on the web interface wasn't working, while the CLI works fine.
Reason is because the option in the HTML is `keepSpecialComments`, it should be `specialComments` instead.
Also changed `*` to `all` as per https://github.com/jakubpawlowicz/clean-css/blob/bbc77a9d8b12fbce85424df322c247472e23ad2e/lib/optimizer/level-1/optimize.js#L521
=> Fix "special comments" option on web interface

lib/optimizer/level-2/remove-unused-at-rules.js, test/optimizer/level-2/remove-unused-at-rules-test.js
Addresses https://github.com/jakubpawlowicz/clean-css/issues/971
=> Ignore quotes when checking @font-face use

README.md
clean-css is a typical dev dependency which should be installed as such
in most of the cases. By providing an example code snippet with the
`--save-dev` option, we're helping the users to do the right thing.
=> Promote installing as dev dependency

lib/options/format.js, lib/writer/helpers.js, test/module-test.js, test/options/format-test.js
See https://github.com/jakubpawlowicz/clean-css/issues/980.
I'm not certain I have implemented this in the way you wanted me too, so feel free to offer improvements
Thanks in advance
=> Add an option for keeping trailing semicolons in rule

README.md
Hi! I noticed that your "npm" badge and "downloads" badge currently both point to the same page for the project on npmjs.org  
I was wondering if you might prefer having the download badge point to a [download chart](https://npmcharts.com/compare/clean-css?minimal=true) instead?
If not, feel free to close and apologies for the drive-by PR 😄
=> Update downloads badge to point to graph of downloads over time 📈

lib/writer/helpers.js, test/optimizer/level-0/optimizations-test.js
The tokenizer will parse a property like `width: ;`, but the property helper for level 0 was not accounting for properties without a value and would throw a `TypeError` if the value was missing.
For example, the following would throw an unhandled error:
```js
const CleanCSS = require('clean-css')
const cleanCss = new CleanCSS({ level: 0 })
cleanCss.minify('a{color:#f00;font-weight:;background:red}')
// TypeError: Cannot read property '0' of undefined
//   at property (./clean-css/lib/writer/helpers.js:80:33)
```
With this change, the property helper now checks for a missing property value before trying to access it.
=> Fix: Prevent error if property block has no value (level 0)

lib/optimizer/level-1/optimize.js, test/optimizer/level-1/optimize-test.js
This MR fixes #1058. 
This:
```
@font-face {
src: local("Some Sans Black Italic");
}
```
became`@font-face{src:local("Some Sans #000 Italic");}`  
instead of `@font-face{src:local("Some Sans Black Italic");}`
Comments / Suggestions welcome :smile:
=> Fix local fonts with colors in name

README.md
See #983 and #1023
README.md change only
Moved semicolonAfterLastProperty from level 1 to format.
=> Update README.md - semicolonAfterLastProperty to format

.travis.yml, appveyor.yml
Also remove the obsolete `sudo: false` from Travis.
=> CI: Remove Node.js 7 and add 8 and 10.

lib/optimizer/level-1/optimize.js, test/optimizer/level-1/optimize-test.js
Add "grid" element to list of elements ignored by removeQuotes.
This prevents required quotes from being removed from single column grids.
Fixes #1078
=> Prevent unquoting on grid elements

lib/reader/rewrite-url.js, test/integration-test.js
Fixes #1122 
I am not sure why single quote explicitly added to data uri. It sounds unreasonable to me.
All old tests have been passed because when mediatype is not omitted, the data uri such as `data:application/x-font-woff;base64,d09GRk9UVE8AAENAAA0AAAAA` will match `isInternal()` check. Nobody actually goes to `isData()` unless the mediatype part was omitted from data uri, such as `data:;base64,d09GRk9UVE8AAENAAA0AAAAA`
=> Fix #1122 - do not wrap data uri with single quote

lib/tokenizer/tokenize.js
`Array.slice()`'s second parameter can be negative which means an offset from the end
Found in my xo branch, which I plan to streamline and open a PR later.
=> tokenize: remove redundant `length` calls

test/module-test.js
These are prohibited in strict mode hence how I noticed it.
EDIT: later we can switch to template literals and make this snippet cleaner.
=> module-test: fix wrong escape characters

README.md
Closes #1146
This PR adds three examples to the readme which shows how to use the `minify` method and what output it returns. I would have found this very helpful when I needed to use the function for the first time.
A few things we could do:
- If you think they take up too much space, the two examples with errors and warnings could be combined into one.
- They could be put somewhere else in the readme, maybe even in their own section.
=> Add examples for minify method

lib/optimizer/configuration/break-up.js, test/optimizer/configuration/break-up-test.js
I wasn't too sure if this was the correct place to put the test, but it failed before the code change and passes now.
This will also handle empty blocks in the middle of a property-value:
```css
div {
background: black, , url("bg.gif"),;
}
```
Happy to move the test if that would be helpful
=> Fixes #1166 - error with trailing comma in property value

lib/reader/read-sources.js
inline=['remote'] is failing when a local file is missing despite the fact that local imports should not be inlined
=> Fix local inlining error

lib/tokenizer/tokenize.js, test/optimizer/level-1/optimize-test.js, test/optimizer/level-2/optimize-test.js, test/tokenizer/tokenize-test.js
CSS variables containing only whitespace will persist from now on.
=> Fixed #1180

lib/reader/apply-source-maps.js, test/fixtures/issue-1194-min.css, test/fixtures/issue-1194.css
Fix the #1194 issue when the source map file for some reason can be empty. In this case handle this situation to avoid `JSON.parse()` an empty string.
=> Fix bug when invalid JSON passed as source map

lib/tokenizer/tokenize.js
This is to prevent DOS via malicious CSS input, see:
https://github.com/clean-css/clean-css/security/code-scanning/12
=> Fixes polynomial regular expression on uncontrolled input data.

lib/tokenizer/tokenize.js
Reset the `isVariable` flag at this point if it's set erroneously.
E.g. `@keyframes Toast--spinner {` — at this point we're certain we aren't a variable.
=> Fixes #1218 - double hyphen in at-rule breaks parsing

lib/optimizer/level-1/value-optimizers/color.js, test/optimizer/level-1/optimize-test.js
The Alpha value in rgba can be a percentage, like `50%` which is the same as `.5`.
Given input:
```css
a{color:rgba(255,255,255,50%)}
```
The expected output should be:
```css
a{color:rgba(255,255,255,50%)}
```
While the actual output is:
```css
a{color:rgba(255,255%,255%,50%)}
```
This PR fixes this bug.
=> Fixes incorrectly appending '%'s to rgba of numbers

.github/workflows/codeql.yml, .github/workflows/test.yml
This PR:
-   Removes Git credentials/SSH keys after checkout as a security precaution by setting `persist-credentials` to false, they are not used after the initial checkout
-   Bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-node` can be [found here](https://github.com/actions/setup-node/releases)
- Changelog for `github/codeql-action` can be [found here](https://github.com/github/codeql-action/blob/main/CHANGELOG.md)
-   Adds latest LTS (Node 18) to test matrix
-   Replaces using deprecated/unsupported Node 15 in linting …
=> Update CI workflows

.github/workflows/codeql.yml, .github/workflows/test.yml
Apologies, forgot to add these in previous PR!
This PR:
-   Declares the minimum permissions for CI workflows to run at the job level, following principle of least privilege; see [related GitHub security post](https://securitylab.github.com/research/github-actions-building-blocks/)
- CodeQL workflow also needs the `security-events` permission set to properly work, see https://github.com/github/codeql-action#usage
-  Adds additional CodeQL security queries, see https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
=> Set CI workflow permissions; add additional CodeQL queries

lib/tokenizer/tokenize.js, test/fixtures/issue-1232-min.css, test/fixtures/issue-1232.css
Hi.
I found a solution how to fix the support of the "@container" keyword.
See opened issue here https://github.com/clean-css/clean-css/issues/1232.
=> Fixes #1232 - add support for the "@container" keyword

README.md
=> docs: README: typo: bufer -> buffer
